FROM postgres:12

RUN mkdir -p /var/lib/postgresql/data/
# RUN chmod -R 777 /var/lib/postresql/data
RUN chmod -R 777 /var/

RUN mkdir -p /docker-entrypoint-initdb.d/
RUN chmod -R 777 /docker-entrypoint-initdb.d/

ENTRYPOINT docker-entrypoint.sh
